create table plsnap_Metadata (
    idMetadata       integer generated by default as identity,
    idSnapshot       integer not null,
    schemaName       varchar2(255),
    objectName       varchar2(255),
    objectType       varchar2(255),
    objectStatus     varchar2(255),
    hasData          varchar2(1),
    part             integer,
    partType         varchar2(255),
    partName         varchar2(255),
    ddl              clob
)
LOB (ddl) store as plsnap_Metadata_ddl
/

comment on table plsnap_Metadata is 'Snapshoted Metadata';

comment on column plsnap_Metadata.idMetadata   is 'Surrogate key';
comment on column plsnap_Metadata.idSnapshot   is 'Snapshot';
comment on column plsnap_Metadata.schemaName   is 'Schema name';
comment on column plsnap_Metadata.objectName   is 'Object name';
comment on column plsnap_Metadata.objectType   is 'Object type';
comment on column plsnap_Metadata.objectStatus is 'Object status';
comment on column plsnap_Metadata.hasData      is 'Object has data';
comment on column plsnap_Metadata.part         is 'Part number';
comment on column plsnap_Metadata.partType     is 'Part type';
comment on column plsnap_Metadata.partName     is 'Part name';
comment on column plsnap_Metadata.ddl          is 'DDL';

alter table plsnap_Metadata
  add constraint plsnap_mtdt_pk
  primary key (idMetadata)
;

alter table plsnap_Metadata
  add constraint plsnap_mtdt_uk1
  unique (idSnapshot, schemaName, objectName, objectType, part)
;

alter table plsnap_Metadata
  add constraint plsnap_mtdt_snap_fk
  foreign key (idSnapshot)
  references plsnap_Snapshot(idSnapshot)
  on delete cascade
;

create index plsnap_mtdt_snap_fk on plsnap_Metadata(idSnapshot);
create index plsnap_mtdt_idObjPtTp on plsnap_Metadata(idSnapshot, partType);

