create table plsnap_Snapshot (
  idSnapshot     integer generated by default as identity,
  idDefinition   integer not null,
  name           varchar2(255) not null,
  tsStatusChange timestamp not null,
  status         varchar2(30) check (status in ('CREATING', 'OK', 'ERROR'))
);

comment on table plsnap_Snapshot is 'Snapshot';

comment on column plsnap_Snapshot.idSnapshot is 'Surrogate key';
comment on column plsnap_Snapshot.idDefinition is 'Snapshot definition';
comment on column plsnap_Snapshot.name is 'Unique name';
comment on column plsnap_Snapshot.tsStatusChange is 'Timestamp of status change';
comment on column plsnap_Snapshot.status is 'Status:{CREATING: Creation of Snapshot is in progress, OK: Created without error, ERROR: Creation failed}';

alter table plsnap_Snapshot
  add constraint plsnap_Snap_pk
  primary key (idSnapshot)
;

alter table plsnap_Snapshot
  add constraint plsnap_Snap_uk1
  unique (name)
;

alter table plsnap_Snapshot
  add constraint plsnap_Snap_Def_fk
  foreign key (idDefinition)
  references plsnap_Definition(idDefinition)
  on delete cascade
;

create index plsnap_Snap_Def_fk on plsnap_Snapshot(idDefinition);
