create table plsnap_Schema (
  idSchema     integer generated by default as identity,
  idDefinition integer not null,
  name         varchar2(255) not null
);

comment on table plsnap_Schema is 'Schema to be snapshoted';

comment on column plsnap_Schema.idSchema is 'Surrogate key';
comment on column plsnap_Schema.idDefinition is 'Definition';
comment on column plsnap_Schema.name is 'Schema name = username';

alter table plsnap_Schema
  add constraint plsnap_Schm_pk
  unique (idSchema)
;

alter table plsnap_Schema
  add constraint plsnap_Schm_uk1
  unique (idDefinition, name)
;

alter table plsnap_Schema
  add constraint plsnap_Schm_Def_fk
  foreign key (idDefinition)
  references plsnap_Definition(idDefinition)
  cascade constraints
;
